### ISSUE TITLE
MS2 spectrum cannot be displayed！

### ISSUE THREAD

**Issue by 3222010198** [Rappsilber-Laboratory/xiSPEC_website#45]
Dear xispec developers, 
I have some problems when using XISPEC V2. After I uploaded the mgf and csv files, the MS2 spectrum of  crosslinked peptides with the same scores cannot be displayed, but the others can be displayed normally.
This image is a screenshot of the problem I encountered, the first row of results has 11 crosslinks with the same score, but it can't display the MS2 information of any of them.
![微信图片_20231106171542](https://github.com/Rappsilber-Laboratory/xiSPEC_website/assets/150008585/02fcbc1d-6f38-47d4-a043-4e0d5aec7327)
![微信图片_20231106171534](https://github.com/Rappsilber-Laboratory/xiSPEC_website/assets/150008585/3ee7ef1b-3449-4e2d-bd02-24fd1d5100c8)
Hope you see this and thank you very much for your help!

**Comment by colin-combe** [comment]
Hi,
if you can share the mgf and csv files with me I'll take a look at what's going wrong.
If you don't want to post your data on GitHub then you can email it to me at colin.combe@ed.ac.uk,
best wishes,
Colin

**Comment by 3222010198** [comment]
Dear Colin,
 I have emailed you the mgf and csv files and look forward to your reply!
best wishes，
Taozi

**Comment by 3222010198** [comment]
Dear Colin,
I have sent the mgf and csv files to your email address, looking forward to your reply!
best wishes

**Comment by colin-combe** [comment]
Hi,

> the MS2 spectrum of crosslinked peptides with the same scores cannot be displayed, but the others can be displayed normally

My guess is that xiSPEC has a problem with several matches for the same spectrum having rank 1. When I tried to test this I found that the upload for https://www.rappsilberlab.org/xiSPEC didn't work. I see other problems there, like the information at https://www.rappsilberlab.org/xiSPEC/help.php can't be accessed.

I can't fix the xiSPEC website right now, but I can offer you the following possible solution:

First, make a user account at https://xiview.org, let me know if you have problems doing this.

Second, add the columns PepPos1 and PepPos2 to your existing .csv file. Just populate these columns with the number '1' for the time being. Your csv file should now meet the requirements at https://xiview.org/xiNET_website/csv-formats.php for "CSV file with peaklists".

Third, upload these files (modified .csv and .mgf) to your xiview acount. I have tested this with your csv file and it works.

You will initially be taken to a page displaying the crosslink network. It will be inaccurate because the peptide position was given as '1' for everything. If you create a CSV file with the correct values for the peptide positions it should be accurate.

You can get to a page displaying just the spectra (similar to the xiSPEC website) by swapping the word "network" for "validate" in the URL or by following the "Spectra only" link from your xiVIEW account's history page.

Let me know how you get on,
cheers,
Colin

**Comment by 3222010198** [comment]
Dear Colin,
I uploaded the csv and mgf like you said and it can be successfully uploaded and shows the network diagram as follows：

![175bc93d2d06bc34796adc681830d64](https://github.com/Rappsilber-Laboratory/xiSPEC_website/assets/150008585/c3e33f0f-8993-442a-b434-63daa701ef42)
![80f8558035fc82c0aa57737fe329e45](https://github.com/Rappsilber-Laboratory/xiSPEC_website/assets/150008585/e4bae89c-df31-43e0-9204-14a277b91f5b)
But no matter I click "SPECTRUM" in the VIEW or replace ""network"" with "validate" in the URL, it doesn't show the MS2 spectrum. And I don't know what's wrong.
hope to get your reply, thanks!

**Comment by 3222010198** [comment]
Dear Colin,
 I have tried again as you suggested and found that XIVIEW displays the MS2 spectrum properly and is very convenient for us!
Thank you very much for your time and patience in responding to the problem I have encountered.
best wishes

**Comment by colin-combe** [comment]
maybe you were having network issues,
cheers,
Colin
